# This is a basic workflow to help you get started with Actions

name: Build Resume PDF

on:
  push:
    branches:
      - 'main'

jobs:  
  build_and_publish:
    runs-on: ubuntu-latest
    container: mosquizz/quarto-ubuntu:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.2

      - name: Render PDF
        run: quarto render ./resume.qmd

      - name: Save PDF
        uses: actions/upload-artifact@v3.1.2
        with:
          name: resume.pdf
          path: ./resume.pdf
