# This is a basic workflow to help you get started with Actions

name: Build Resume PDF

on: [push, workflow_dispatch]

jobs:  
  build_and_publish:
    runs-on: ubuntu-latest
    container: mosquizz/quarto-ubuntu:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.2
        
      - name: Check Quarto tools
        run: |
          quarto list tools
          quarto install tinytex
          quarto list tools

      - name: Render PDF
        run: quarto render ./resume.qmd

      - name: Save PDF
        uses: actions/upload-artifact@v3.1.2
        with:
          name: resume.pdf
          path: ./resume.pdf
